---
- hosts: local
  become: yes
  become_method: sudo
  tasks:
  - name: unzipping
    unarchive: 
     src: oracle-xe-11.2.0-1.0.x86_64.rpm.zip
     dest: /home/sailesh/Desktop
  - name: installing required packages
    apt: 
     name: ['alien', 'libaio1', 'unixodbc'] 
     state: present
  - name: Entering into disk1
    command: cd Disk1/
  - name: Converting RPM package format to DEB package
    command: alien --scripts -d oracle-xe-11.2.0-1.0.x86_64.rpm
  - name: Create the required chkconfig script
    copy:
     dest: "/sbin/chkconfig"
     content: |
       #!/bin/bash
       # Oracle 11gR2 XE installer chkconfig hack for Ubuntu
       file=/etc/init.d/oracle-xe
       if [[ ! `tail -n1 $file | grep INIT` ]]; then
         echo >> $file
         echo '### BEGIN INIT INFO' >> $file
         echo '# Provides: OracleXE' >> $file
         echo '# Required-Start: $remote_fs $syslog' >> $file
         echo '# Required-Stop: $remote_fs $syslog' >> $file
         echo '# Default-Start: 2 3 4 5' >> $file
         echo '# Default-Stop: 0 1 6' >> $file
         echo '# Short-Description: Oracle 11g Express Edition' >> $file
         echo '### END INIT INFO' >> $file
         fi
           update-rc.d oracle-xe defaults 80 01
     mode: 0755
  - name: Setting kernel parameters for Oracle 11gR2 XE
    copy:
     dest: "/etc/sysctl.d/60-oracle.conf"
     content: |
       # Oracle 11g XE kernel parameters
       fs.file-max=6815744
       net.ipv4.ip_local_port_range=9000 65000
       kernel.sem=250 32000 100 128
       kernel.shmmax=536870912
  - name: Verify the change
    command: Verify the change using the command
  - name: loading the kernel parameters
    command: service procps start
  - name: Verifying the new parameters
    command: sysctl -q fs.file-max
  - name: Setting up /dev/shm mount point for Oracle
    copy:
     dest: "/etc/rc2.d/S01shm_load"
     content: |
       #!/bin/sh
       case "$1" in
       start)
         mkdir /var/lock/subsys 2>/dev/null
         touch /var/lock/subsys/listener
         rm /dev/shm 2>/dev/null
         mkdir /dev/shm 2>/dev/null
         *)
           echo error
           exit 1
           ;;
       esac  
     mode: 0755
  - name: Executing multiple commands
    shell: |
     sudo ln -s /usr/bin/awk /bin/awk
     sudo mkdir /var/lock/subsys
     sudo touch /var/lock/subsys/listener
     sudo "hello"